version: '3.7'

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users_service
      - management_service

  users_service:
    build: ./users
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./users/:/app/
    environment:
      - DATABASE_URI=postgresql://users_db_username:users_db_password@users_db/users_db
      - MANAGEMENT_SERVICE_HOST_URL=http://management_service:8000/api/v1/management
    depends_on:
      - users_db

  users_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_users:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=users_db_username
      - POSTGRES_PASSWORD=users_db_password
      - POSTGRES_DB=users_db

  management_service:
    build: ./management
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./management/:/app/
    environment:
      - DATABASE_URI=postgresql://management_db_username:management_db_password@management_db/management_db
      - USERS_SERVICE_HOST_URL=http://users_service:8000/api/v1

  management_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_management:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=management_db_username
      - POSTGRES_PASSWORD=management_db_password
      - POSTGRES_DB=management_db

volumes:
  postgres_data_users:
  postgres_data_management:
