version: '3.7'

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users_service
#      - tasks_service

  users_service:
    build: ./users
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./users/:/app/
    environment:
      - DATABASE_URI=postgresql://users_db_username:users_db_password@users_db/users_db
      - TASKS_SERVICE_HOST_URL=http://tasks_service:8000/api/v1/tasks
    depends_on:
      - users_db

  users_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_users:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=users_db_username
      - POSTGRES_PASSWORD=users_db_password
      - POSTGRES_DB=users_db

#  tasks_service:
#    build: ./tasks
#    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
#    volumes:
#      - ./tasks/:/app/
#    environment:
#      - DATABASE_URI=postgresql://tasks_db_username:tasks_db_password@tasks_db/tasks_db
#
#  tasks_db:
#    image: postgres:12.1-alpine
#    volumes:
#      - postgres_data_tasks:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=tasks_db_username
#      - POSTGRES_PASSWORD=tasks_db_password
#      - POSTGRES_DB=tasks_db

volumes:
  postgres_data_users:
#  postgres_data_tasks:
